version: '3.3'
volumes:
  data:
networks:
  poc-microservice:
    driver: bridge
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    expose:
      - 3306
    container_name: poc-microservice-mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ENGLAND_IS_MY_CITY
      - MYSQL_DATABASE=microservices
    networks:
      - poc-microservice

  gateway:
    build:
      context: .
    container_name: poc-microservice-gateway
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT_MICROSERVICE_GATEWAY=3000
      - URL_MICROSERVICE_USER=127.0.0.1
      - PORT_MICROSERVICE_USER=3002
    networks:
      - poc-microservice
    ports:
      - 3000:3000
      - 9229:9229

  users:
    build:
      context: ../users
    container_name: poc-microservice-users
    restart: always
    volumes:
      - ../users:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT_MICROSERVICE_USER=3002
      - URL_MICROSERVICE_DATABASE=127.0.0.1
      - PORT_MICROSERVICE_DATABASE=3001
    networks:
      - poc-microservice
    ports:
      - 3002:3002
      - 9230:9229

  database:
    build:
      context: ../database
    container_name: poc-microservice-database
    restart: always
    volumes:
      - ../database:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT_MICROSERVICE_DATABASE=3001
      - MYSQL_PORT=3306
      - MYSQL_URL=mysql
    networks:
      - poc-microservice
    depends_on:
      - mysql
    ports:
      - 3001:3001
      - 9231:9229


