version: '3.3'
volumes:
  data:
services:
  gateway:
    build:
      context: .
      args:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    container_name: poc-microservice-gateway
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
#    depends_on:
#      - export
    ports:
      - 3000:3000
      - 3002:3002
      - 9229:9229

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    container_name: poc-microservice-mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ENGLAND_IS_MY_CITY
      - MYSQL_DATABASE=microservices
