version: '3.3'
volumes:
  data:
networks:
  poc-microservice:
    driver: bridge
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    expose:
      - 3306
    container_name: poc-microservice-mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ENGLAND_IS_MY_CITY
      - MYSQL_DATABASE=microservices
    networks:
      - poc-microservice

  gateway:
    build:
      context: .
      args:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    container_name: poc-microservice-gateway
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - poc-microservice
    ports:
      - 3000:3000
      - 9229:9229

  database:
    build:
      context: ../database
      args:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    container_name: poc-microservice-database
    restart: always
    volumes:
      - ../database:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - poc-microservice
    depends_on:
      - mysql
    ports:
      - 3001:3001
      - 9231:9229

  users:
    build:
      context: ../users
      args:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    container_name: poc-microservice-users
    restart: always
    volumes:
      - ../users:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - poc-microservice
    ports:
      - 3002:3002
      - 9230:9229
