kind: Service
apiVersion: v1
metadata:
    name: user
    namespace: {{.Values.metadata.namespace}}
spec:
    type: NodePort
    selector:
        app: user
    ports:
        - protocol: TCP
          port: {{.Values.container.port}}
          targetPort: {{.Values.container.port}}
          nodePort: {{.Values.service.nodePort}}
