apiVersion: v1
kind: Service
metadata:
    name: {{ include "gateway.fullname" . }}
    namespace: {{.Values.metadata.namespace}}
    labels:
        app.kubernetes.io/name: {{ include "gateway.name" . }}
        helm.sh/chart: {{ include "gateway.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          nodePort: {{.Values.service.nodePort}}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
