apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" . }}
  namespace: {{.Values.metadata.namepsace}}
  labels:
    app.kubernetes.io/name: {{ include "users.name" . }}
    helm.sh/chart: {{ include "users.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{.Values.service.nodePort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "users.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
