apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    namespace: {{.Values.metadata.namespace}}
    labels:
        app: mysql
spec:
    replicas: {{.Values.replicas}}
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:{{.Values.image.tag}}
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: ENGLAND_IS_MY_CITY
                      - name: MYSQL_DATABASE
                        value: microservices
                  ports:
                      - containerPort: {{ .Values.container.port}}
