apiVersion: v1
kind: Service
metadata:
    name: {{ include "mysql.fullname" . }}
    namespace: {{.Values.namepsace}}
    labels:
        app.kubernetes.io/name: {{ include "mysql.name" . }}
        helm.sh/chart: {{ include "mysql.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          nodePort: {{ .Values.service.nodePort }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "mysql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
