kind: Service
apiVersion: v1
metadata:
  name: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
