apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: lcamilo/gateway_database:alpha
          env:
            - name: URL_MICROSERVICE_DATABASE
              value: '192.168.1.10'
            - name: MYSQL_PORT
              value: '30001'
            - name: MYSQL_URL
              value: '192.168.1.10'
          ports:
            - containerPort: 3001
