apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: lcamilo/gateway_users:alpha
          env:
            - name: URL_MICROSERVICE_DATABASE
              value: '192.168.1.10'
            - name: PORT_MICROSERVICE_DATABASE
              value: '30001'
            - name: URL_MICROSERVICE_USER
              value: '192.168.1.10'
            - name: PORT_MICROSERVICE_USER
              value: '3002'
          ports:
            - containerPort: 3002
