apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 5
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: lcamilo/gateway_users:0.0.2
          env:
            - name: URL_MICROSERVICE_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: URL_MICROSERVICE_DATABASE
                  name: poc-microservice
            - name: PORT_MICROSERVICE_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: PORT_MICROSERVICE_DATABASE
                  name: poc-microservice
          ports:
            - containerPort: 3002
